stackabletech/actions

- README.md
- build-container-image/action.yml
- Remove comments from inside a multi-line command
- Improve outputs and docs
> [!IMPORTANT]
> :green_circle: Pending test run: https://github.com/stackabletech/trino-lb/actions/runs/11258419701
> fix: remove comments from multi-line command

- build-container-image/action.yml
- Add `--load` option to `docker buildx build`
Otherwise `docker push` doesn't work in later steps.
- Add log groupings to reduce noise
> fix: Add --load to docker buildx build command

- publish-image/action.yml
Same thing as https://github.com/stackabletech/operator-templating/pull/448, but for our product images. It probably makes sense for the same person to review both this PR and the other.
---
Use OCI type for PURLs, according to https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#oci
This is more correct in general and most importantly makes the PURL equal to the one Trivy generates for our container images.
This PR is a bit more complicated than the one for operators, since I had to extract the product name (e.g. "kafka") and the architecture before generating the PURL.
I also added another small change to this PR:
The `--source-name` passed to Syft is now just the name of the image. Currently, it would be `sdp/kafka`. This change changes it to just `kafka`. The parameter …
> fix: make PURLs use oci type / fixed SBOM component name

- .github/workflows/pr_actions-smoke-test.yml
- build-container-image/action.yml
- build-product-image/action.yml
- free-disk-space/action.yml
There are different paths when running `free-disk-space` directly in actions from this repository (eg: in smoke tests) vs being called from a remote repository.
There doesn't appear to be an easy way to work around it.
Workflows using the `build-product-image` or `build-container-image` actions will need to run `free-disk-space` explicitly beforehand.
Eg:
```yml
steps:
- name: Free Disk Space
uses: stackabletech/actions/free-disk-space@x.x.x
- name: Checkout Repository
uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
- name: Build Product Image
id: build
uses: stackabletech/actions/build-product-image@x.x.x
with:
product-name: ${{ env.PRODUCT_NAME }}
product-version: ${{ matrix.versions }}
build-cache-password: ${{ secrets.BUILD_CACHE_NEXUS_PASSWORD }}
```
> fix!: Remove free-disk-space from the build-*-image actions

- build-product-image/README.md
- build-product-image/action.yml
Previously the SDP release version was hard-coded to 0.0.0-dev. This needs to be configurable before it can be used by the release workflows.
> feat(build-product-image): Add an input for sdp-version

- run-integration-test/action.yml
Part of https://github.com/stackabletech/decisions/issues/33
This adds support to set the number of nodes, disk size and cluster TTL in the integration test config file.
> feat: Support nodes, disk and TTL values in integration test config

- run-integration-test/README.md
- run-integration-test/instances.yml
This PR adds mappings for k3s and RKE2 clusters, which both support nodes > 1 (kind on Replicated only supports single node clusters).
> feat(run-integration-test): Add k3s and RKE2 cluster mappings

- run-pre-commit/README.md
- run-pre-commit/action.yml
This adds support to install nix when running pre-commit. This is useful for repositories which have pre-commit hooks requiring nix to run them.
> feat(run-pre-commit): Add support to install nix

- .github/workflows/pr_actions-smoke-test.yml
- build-product-image/README.md
- build-product-image/action.yml
Part of https://github.com/stackabletech/docker-images/pull/948
Changes for the `build-product-image` action:
- Add a `extra-tag-data` input to allow extra tag data in the image manifest tag, like PR numbers: `3.9.2-stackable0.0.0-dev-pr321-arm64`.
- Add a `suggested-image-index-manifest-tag` output for subsequent jobs to make use of.
> feat(build-product-image): Add extra-tag-data input

- .github/workflows/release_interu.yml
The `release` job needs to run _after_ the build job.
> ci: Add missing needs key

- .github/workflows/build_interu.yml
- .github/workflows/release_interu.yml
The `softprops/action-gh-release` had a broken file upload in version `2.2.0`. The issue was fixed in `2.2.1`.
See https://github.com/softprops/action-gh-release/pull/562
> ci: Bump broken action

- .github/workflows/pr_actions-smoke-test.yml
- run-integration-test/README.md
- run-integration-test/action.yml
~Blocked by #30~, part of https://github.com/stackabletech/issues/issues/659
> feat(run-integration-test): Integrate interu tool into action

- .scripts/get_manifest_digest.sh
- README.md
- build-product-image/README.md
- build-product-image/action.yml
- publish-index-manifest/action.yml
- tools/interu/fixtures/test-definition.yaml
Part of https://github.com/stackabletech/infrastructure/issues/142
Updates registry references to oci. Uses new image-tools version containing oci reference changes.
> chore: update to oci references

- run-pre-commit/action.yml
This PR enables caching for:
- **pip:** Reduces time from 49s to 12s (in this repo), which is a 75% decrease in time
- **rust:** Hard to measure individually, but it roughly went from 10s to 3s (in this repo), which is a 70% decrease in time
Very simple testing in https://github.com/stackabletech/operator-rs/pull/1014 showed a reduction from 1m2s to 23s, which is roughly a 62% speedup (for run 1+n).
---
It also enables pinning pre-commit to a specific version. Before, the action always installed the latest available version.
> feat(run-pre-commit): Enable caching, support pre-commit pinning

- run-pre-commit/README.md
> docs(run-pre-commit): Add new pre-commit-version input to README

- send-slack-notification/README.md
- send-slack-notification/action.yaml
This PR adds a new send-slack-notification action with support for threading. The action will create threads for each individual workflow run. This allows multiple attempts of the same run to be displayed as a thread. This is mainly used in docker-image workflows.
> feat: Add send-slack-notification action

- send-slack-notification/action.yaml
This PR extends the capabilities of the send-slack-notification action:
- It is now possible to send failure **and success** messages
- The Slack thread ID retrieval is now idempotent
> feat(send-slack-notification): Send failure and success message

- build-container-image/action.yml
- build-product-image/action.yml
- publish-image/action.yml
- publish-index-manifest/action.yml
- run-pre-commit/action.yml
- send-slack-notification/action.yaml
- shard/action.yml
* Bump actions/download-artifact to 4.3.0
* Bump cachix/install-nix-action to 31.4.1
* Bump dtolnay/rust-toolchain to latest commit
* Bump actions/setup-python to 5.6.0
* Bump anchore/sbom-action to 0.20.1
* Bump sigstore/cosign-installer to 3.9.1
* Bump docker/setup-buildx-action to 3.11.1
> chore: Bump actions to latest versions

- run-pre-commit/action.yaml
This PR introduces the following changes:
- It now uses a Rust cache (if Rust is installed) to cache build artifacts to speed up subsequent workflow runs
- Abort the Nix install right at the start if the token is missing. Previously, a whole bunch of unnecessary setup was done before the workflow was eventually aborted. It now immediately aborts to save runtime.
> feat(run-pre-commit): Use Rust cache (if Rust is installed)

- run-integration-test/action.yaml
This PR introduces two small changes:
- It removes the conditional workflow runs (IONOS is no longer a supported and/or used distribution)
- It bumps stackablectl to 1.1.0.
> ci(run-integration-test): Remove superfluous conditionals

- .gitattributes
- .github/workflows/pr_actions-smoke-test.yml
- run-integration-test/README.md
- run-integration-test/action.yaml
- run-integration-test/health
- send-slack-notification/README.md
- send-slack-notification/action.yaml
- send-slack-notification/templates/container-image-build/failure.tpl
- send-slack-notification/templates/integration-test/failure.tpl
- send-slack-notification/templates/integration-test/success.tpl
This PR adds the following changes:
- The `health` output of the `run-integration-test` action returns a "weather" icon representing the success rate of the last few test runs similar to how Jenkins does it.
- The `send-slack-notification` action now supports two types of notifications: `container-image-build` and `integration-test`. They both expect different inputs and will send different Slack messages.
> feat: Improve the Slack notification action

- send-slack-notification/templates/integration-test/failure.tpl
- send-slack-notification/templates/integration-test/success.tpl
> fix: Remove superfluous double quote from templates

- run-integration-test/kustomize/bases/opentelemetry-operator/kustomization.yml
This gets past the [invalid values JSON](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1805) schema [now enforced by Helm](https://github.com/helm/helm/releases/tag/v3.18.5).
> fix(run-integration-test/telemetry): Bump otel-operator to 0.93.0

- .scripts/actions/get_platform.sh
- run-integration-test/README.md
- run-integration-test/action.yaml
Add support to pin `kubectl` and `helm` versions to avoid breakages like https://github.com/stackabletech/zookeeper-operator/actions/runs/17124645488 which was fixed in #64.
> feat(run-integration-test): Support pinned kubectl and helm versions

- send-slack-notification/action.yaml
- send-slack-notification/templates/integration-test/failure.tpl
- send-slack-notification/templates/integration-test/success.tpl
This includes the operator name in the integration test notification message, as the `text` field seems to do nothing (?).
> fix(send-slack-notification): Include operator name in message

- .scripts/actions/get_build_arguments.sh
- build-container-image/README.md
- build-container-image/action.yaml
This PR adds support to specify Docker build arguments in the `build-container-image` action. This will for example be useful when building operator images using this action instead of relying on the Makefile.
> feat(build-container-image): Support Docker build arguments

- run-integration-test/instances.yaml
Part of https://github.com/stackabletech/issues/issues/761
This adds arm64 nodes for VM-based clusters (kind, k3s, rke2) to the instance file. This is currently an **alpha** feature enabled for us.
> feat(run-integration-test): Add arm64 instances to kind, k3s, rke2

- README.md
- publish-helm-chart/README.md
- publish-helm-chart/action.yaml
This PR adds a new `publish-helm-chart` action:
- Packages the Helm Chart
- Pushes the chart
- Signs the chart
> feat: Add publish-helm-chart action

- .scripts/actions/install_boil.sh
- .scripts/actions/install_helm.sh
- .scripts/actions/install_interu.sh
- .scripts/actions/install_kubectl.sh
- .scripts/actions/install_kubectl_kuttl.sh
- .scripts/actions/install_stackablectl.sh
- RELEASE.md
- build-product-image/action.yaml
- publish-helm-chart/action.yaml
- run-integration-test/action.yaml
- setup-k8s-tools/action.yaml
- setup-tools/action.yaml
- shard/action.yaml
This allows us to abstract away the installation process into scripts which can be used by the two setup actions and other local actions. This removes the dependency on the setup actions for other local actions which would have been painful to manage going forward.
> refactor: Use install scripts

- shard/action.yaml
Some product names contain dashes and `jq` couldn't handle them before.
> fix(shard): Handle dashes in keys
